<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>TableDependency.SqlClient.El.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>TableDependency.SqlClient</AssemblyTitle>
    <Description>TableDependency.SqlClient is a C# component used to receive Microsoft SQL Server © database notifications when a table record has been changed.</Description>
    <Company>Christian Del Bianco</Company>
    <Product>TableDependency.SqlClient</Product>
    <Copyright>Copyright Christian Del Bianco © 2015-2017</Copyright>
    <AssemblyVersion>6.1.0.0</AssemblyVersion>
    <FileVersion>6.1.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TableDependency\TableDependency.csproj" />
  </ItemGroup>
</Project>