<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>TableDependency.El.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>TableDependency</AssemblyTitle>
    <Description>TableDependency is C# base class for TableDependency.SqlClient.</Description>
    <Company>Christian Del Bianco</Company>
    <Product>TableDependency</Product>
    <Copyright>Copyright Christian Del Bianco © 2015-2017</Copyright>
    <AssemblyVersion>6.1.0.0</AssemblyVersion>
    <FileVersion>6.1.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>
</Project>